name: analyze
on:
  push:
    paths: ["data/**","analysis/python/**","web/**"]
  pull_request:
    paths: ["data/**","analysis/python/**","web/**"]
jobs:
  build:
    # Allow docs updates to be pushed back to the repository
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r analysis/python/requirements.txt
      - name: Validate problems.csv against schema
        run: python3 analysis/python/validate.py
      - run: python analysis/python/triage_impact_uncertainty.py
      - run: python analysis/python/micmac.py
      - run: python analysis/python/ism.py
      - run: python analysis/python/reports.py
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r analysis/python/requirements.txt
          # نصب صریح pytest برای اطمینان (اگر در requirements نبود/کش وجود داشت)
          pip install -U pytest
      - name: Run unit tests
        run: python3 -m pytest -q analysis/python/tests
      - name: Commit docs
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@example.com"
          git add docs || true
          git commit -m "ci: update docs" || true
          git push || true
